### ISSUE TITLE
iOS simulator vs actual device

### ISSUE THREAD

**Issue by jcarolus** [lochstar/nativescript-cast#10]
I just ran into this issue that the Simulator will show the cast button, while on an actual device it won't. This is because of `Xcode 10 Warning: If developing using Xcode 10 and targeting iOS devices running iOS 12 or higher, the "Access WiFi Information" capability is required in order to discover and connect to Cast devices.` mentioned on https://developers.google.com/cast/docs/ios_sender/

It should be an easy fix adding an `app.entitlements` file to the demo apps iOS resources - I may be able to pick this up later and create a PR.

**Comment by lochstar** [comment]
Thanks. This didn't come up because I've only tested on iOS 11. It looks like you need a paid account so your provisioning profile can have the `Access WiFi Information capability` enabled.

Do you know if `app.entitlements` can be bundled as part of a plugin? Or will it have to be a manul step when setting up your iOS app?
